/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(250),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BOOLEAN,
	weight_kg DECIMAL
);

ALTER TABLE animals ADD species VARCHAR(250);

-- Day-3

CREATE TABLE owners (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	full_name VARCHAR(255),
	age INTEGER,
	PRIMARY KEY(id)
);
